---
tags: []
layout: editor_bottom
type: problem
extra_visible: false
language: 
teacher_info: 'Perfecto, ya tenemos nuestra línea, pero hay un inconveniente: el cabezal
  nos quedó en una posición incómoda para dibujar la siguiente línea...'
manual_evaluation: false
